# Generated by Django 5.2.7 on 2025-10-02 14:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLeaveDay',
            fields=[
                ('day_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField(unique=True, verbose_name='日付')),
                ('fiscal_year', models.PositiveIntegerField(verbose_name='対象年度')),
                ('description', models.CharField(max_length=100, verbose_name='摘要')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
            ],
            options={
                'verbose_name': '一斉有給取得日',
                'verbose_name_plural': '一斉有給取得日',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False, verbose_name='部署ID')),
                ('department_name', models.CharField(max_length=100, unique=True, verbose_name='部署名')),
            ],
            options={
                'verbose_name': '部署',
                'verbose_name_plural': '部署',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('holiday_date', models.DateField(primary_key=True, serialize=False, verbose_name='日付')),
                ('description', models.CharField(max_length=100, verbose_name='祝日名')),
            ],
            options={
                'verbose_name': '祝日',
                'verbose_name_plural': '祝日',
            },
        ),
        migrations.CreateModel(
            name='PreApprovedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='社員ID番号')),
                ('is_registered', models.BooleanField(default=False, verbose_name='登録完了フラグ')),
            ],
            options={
                'verbose_name': '事前承認ユーザー',
                'verbose_name_plural': '事前承認ユーザー',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='年度')),
                ('time_leave_limit_minutes', models.PositiveIntegerField(default=480, verbose_name='時間休上限（分）')),
            ],
            options={
                'verbose_name': 'システム設定',
                'verbose_name_plural': 'システム設定',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='社員ID番号')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入社日')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False, verbose_name='申請ID')),
                ('application_type', models.CharField(choices=[('NEW', '新規申請'), ('CANCEL', '取消申請')], default='NEW', max_length=10, verbose_name='申請種別')),
                ('leave_type', models.CharField(choices=[('PAID', '有給休暇'), ('AM_HALF', '午前半休'), ('PM_HALF', '午後半休'), ('TIME', '時間休'), ('SPECIAL', '慶弔休暇'), ('CHILDCARE', '育児休暇'), ('NURSING', '介護休暇'), ('SICK', '病欠'), ('ABSENCE', '欠勤'), ('OTHER', 'その他休暇')], max_length=20, verbose_name='休暇種別')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('reason', models.TextField(blank=True, max_length=200, verbose_name='申請理由')),
                ('status', models.CharField(choices=[('APPLYING', '申請中'), ('APPROVED', '承認済'), ('REJECTED', '却下'), ('REMANDED', '差し戻し'), ('CANCELLED', '取り消し済')], default='APPLYING', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('approval_route', models.JSONField(blank=True, null=True, verbose_name='承認ルート')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
                ('cancellation_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_applications', to='leaves.application', verbose_name='取消対象申請')),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_tasks', to=settings.AUTH_USER_MODEL, verbose_name='現在の承認者')),
            ],
            options={
                'verbose_name': '休暇申請',
                'verbose_name_plural': '休暇申請',
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False, verbose_name='履歴ID')),
                ('action', models.CharField(choices=[('APPLY', '申請'), ('APPROVE', '承認'), ('REJECT', '却下'), ('REMAND', '差し戻し'), ('CANCEL', '取り消し')], max_length=10, verbose_name='アクション')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='処理日時')),
                ('comment', models.TextField(blank=True, max_length=200, verbose_name='コメント')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_histories', to='leaves.application', verbose_name='関連申請')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_histories', to=settings.AUTH_USER_MODEL, verbose_name='処理者')),
                ('original_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_histories', to=settings.AUTH_USER_MODEL, verbose_name='本来の承認者')),
            ],
            options={
                'verbose_name': '承認履歴',
                'verbose_name_plural': '承認履歴',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='所属ID')),
                ('is_primary', models.BooleanField(default=True, verbose_name='主務フラグ')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='上長')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.department', verbose_name='部署')),
            ],
            options={
                'verbose_name': '所属情報',
                'verbose_name_plural': '所属情報',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaves.assignment', verbose_name='申請時所属'),
        ),
        migrations.AddField(
            model_name='application',
            name='company_leave_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='leaves.companyleaveday', verbose_name='関連一斉取得日'),
        ),
        migrations.CreateModel(
            name='BreakTime',
            fields=[
                ('break_time_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('description', models.CharField(max_length=100, verbose_name='摘要')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='break_times', to=settings.AUTH_USER_MODEL, verbose_name='対象ユーザー')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='break_times', to='leaves.department', verbose_name='対象部署')),
            ],
            options={
                'verbose_name': '休憩時間',
                'verbose_name_plural': '休憩時間',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False, verbose_name='グループID')),
                ('group_name', models.CharField(max_length=100, verbose_name='グループ名')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='leaves.department', verbose_name='所属部署')),
            ],
            options={
                'verbose_name': 'グループ',
                'verbose_name_plural': 'グループ',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaves.group', verbose_name='グループ'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False, verbose_name='役職ID')),
                ('role_name', models.CharField(max_length=100, unique=True, verbose_name='役職名')),
                ('role_level', models.IntegerField(help_text='承認ルート決定に使用。数値が小さいほど下位。', verbose_name='階層レベル')),
                ('view_scope', models.CharField(choices=[('TEAM', 'チーム'), ('GROUP', 'グループ'), ('DEPARTMENT', '部署'), ('ALL', '全社')], default='TEAM', max_length=20, verbose_name='カレンダー表示範囲')),
                ('is_approval_endpoint', models.BooleanField(default=False, help_text='この役職が部署等の承認ルートの終点となる場合にTrue', verbose_name='承認ルート終点フラグ')),
                ('approval_order', models.PositiveSmallIntegerField(blank=True, help_text='1次承認、2次承認など。数値が小さい順に承認される。', null=True, verbose_name='承認順序')),
                ('deputy_role', models.ForeignKey(blank=True, help_text='この役職の代理承認を行う役職', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaves.role', verbose_name='代理役職')),
            ],
            options={
                'verbose_name': '役職',
                'verbose_name_plural': '役職',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaves.role', verbose_name='役職'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False, verbose_name='チームID')),
                ('team_name', models.CharField(max_length=100, verbose_name='チーム名')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='leaves.group', verbose_name='所属グループ')),
            ],
            options={
                'verbose_name': 'チーム',
                'verbose_name_plural': 'チーム',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaves.team', verbose_name='チーム'),
        ),
        migrations.CreateModel(
            name='TimeLeaveSlot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False, verbose_name='スロットID')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('calculated_minutes', models.PositiveIntegerField(verbose_name='計算後の取得時間(分)')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_leave_slots', to='leaves.application', verbose_name='関連申請')),
            ],
            options={
                'verbose_name': '時間休スロット',
                'verbose_name_plural': '時間休スロット',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='年度')),
                ('carried_over_minutes', models.PositiveIntegerField(default=0, verbose_name='前年繰越（分）')),
                ('granted_minutes', models.PositiveIntegerField(default=0, verbose_name='今年度付与（分）')),
                ('used_minutes', models.PositiveIntegerField(default=0, verbose_name='合計利用実績（分）')),
                ('half_leave_used_count', models.PositiveSmallIntegerField(default=0, verbose_name='半休利用回数')),
                ('time_leave_used_minutes', models.PositiveIntegerField(default=0, verbose_name='時間休利用実績（分）')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '休暇残高',
                'verbose_name_plural': '休暇残高',
                'constraints': [models.UniqueConstraint(fields=('user', 'year'), name='unique_user_year_balance')],
            },
        ),
    ]
