# Generated by Django 5.2.7 on 2025-10-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='申請の合計時間（分）'),
        ),
    ]
