# Generated by Django 5.2.7 on 2025-10-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_application_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalhistory',
            name='action',
            field=models.CharField(choices=[('APPLY', '申請'), ('RESUBMIT', '再申請'), ('APPROVE', '承認'), ('REJECT', '却下'), ('REMAND', '差し戻し'), ('CANCEL', '取り消し')], max_length=10, verbose_name='アクション'),
        ),
    ]
